# Generated by Django 4.2.16 on 2025-12-15 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='运营线路编码')),
                ('code', models.IntegerField(verbose_name='线路代码')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='线路名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '运营线路',
                'verbose_name_plural': '运营线路',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='站点ID')),
                ('travel_area_id', models.IntegerField(blank=True, null=True, verbose_name='旅行区ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='站点代码')),
                ('telecode', models.CharField(max_length=10, unique=True, verbose_name='站点电报码')),
                ('shortname', models.CharField(blank=True, max_length=20, null=True, verbose_name='站点简称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='列车编码')),
                ('code', models.CharField(max_length=20, verbose_name='列车代码')),
                ('capacity', models.IntegerField(verbose_name='列车运量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '列车',
                'verbose_name_plural': '列车',
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='线路站点顺序')),
                ('distance_to_previous', models.IntegerField(default=0, verbose_name='与上一站距离(公里)')),
                ('total_distance', models.IntegerField(default=0, verbose_name='累计运输距离(公里)')),
                ('is_start', models.BooleanField(default=False, verbose_name='是否起始站点')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否终点站点')),
                ('must_stop', models.BooleanField(default=True, verbose_name='是否必须停靠')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('next_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_stations', to='data_management.station', verbose_name='下一站')),
                ('previous_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_stations', to='data_management.station', verbose_name='上一站')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='data_management.route', verbose_name='运营线路')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.station', verbose_name='站点')),
            ],
            options={
                'verbose_name': '线路站点',
                'verbose_name_plural': '线路站点',
                'db_table': 'route_station',
                'ordering': ['route', 'sequence'],
                'unique_together': {('route', 'station')},
            },
        ),
        migrations.CreateModel(
            name='PassengerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True, verbose_name='序号')),
                ('route_station_sequence', models.IntegerField(blank=True, null=True, verbose_name='线路站点顺序')),
                ('operation_date', models.DateField(verbose_name='运行日期')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='到达时间')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='出发时间')),
                ('passengers_in', models.IntegerField(default=0, verbose_name='上客量')),
                ('passengers_out', models.IntegerField(default=0, verbose_name='下客量')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='车票价格')),
                ('start_station_telecode', models.CharField(blank=True, max_length=10, null=True, verbose_name='起点站电报码')),
                ('end_station_telecode', models.CharField(blank=True, max_length=10, null=True, verbose_name='终点站电报码')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='收入')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.route', verbose_name='运营线路')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.station', verbose_name='站点')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.train', verbose_name='列车')),
            ],
            options={
                'verbose_name': '客运记录',
                'verbose_name_plural': '客运记录',
                'db_table': 'passenger_flow',
                'ordering': ['-operation_date', 'route', 'train', 'station'],
                'indexes': [models.Index(fields=['operation_date'], name='passenger_f_operati_bc967f_idx'), models.Index(fields=['route', 'operation_date'], name='passenger_f_route_i_4274f6_idx'), models.Index(fields=['station', 'operation_date'], name='passenger_f_station_5dbe5a_idx'), models.Index(fields=['train'], name='passenger_f_train_i_a0ab72_idx')],
            },
        ),
    ]
