# Generated by Django 4.2.16 on 2025-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='platform_count',
            field=models.IntegerField(default=2, verbose_name='站台数量'),
        ),
    ]
